#docker network create --driver=bridge --subnet 172.20.0.0/16 --gateway 172.20.0.1 melon-net
version: '3.9'
services:
  stock_db:
    image: postgres:latest
    container_name: stock_db
    networks:
      - melon-net
    restart: always
    ports:
      - "15432:5432"
    env_file:
      - .env.stock_db
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./stock_db:/var/lib/postgresql/data

  stock:
    image: stock:latest
    container_name: stock
    networks:
      - melon-net
    #    restart: always
    ports:
      - "18000:8000"
    env_file:
      - .env
    volumes:
      - ./logs_stock:/app/logs
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - stock_db
      -
networks:
  melon-net:
    name: melon-net
    external: true