"""애플리케이션 전역 상수 정의"""

# 시스템 설정
MAX_WORKER_COUNT = 10
BLACKLIST_RETENTION_DAYS = 30
DEFAULT_PRICE_HISTORY_YEARS = 5
DEFAULT_PRICE_HISTORY_DAYS = 365

# 국가별 정규식 패턴
KOREAN_STOCK_PATTERN = r'(\d{5}[0-9KLMN])'
AMERICA_STOCK_PATTERN = r'([a-zA-Z\s\.]*)'

# TradingView API 응답 데이터 인덱스
TICKER_INDEX = 0
DIVIDEND_YIELD_INDEX = 6
DIVIDEND_PAYOUT_RATIO_INDEX = 7
CONTINUOUS_DIVIDEND_INDEX = 8
CASH_FLOW_INDEX = 9
NET_INCOME_INDEX = 10

# 가격 설정
VOLUME_SPLIT_RATIO = 0.5
KOREAN_PRICE_MARKUP_LEVEL1 = 1.080
KOREAN_PRICE_MARKUP_LEVEL2 = 1.155
USA_PRICE_MARKUP_LEVEL1 = 1.080
USA_PRICE_MARKUP_LEVEL2 = 1.155

# 기술적 지표 기본 설정
BOLLINGER_WINDOW = 20
BOLLINGER_STD_DEV = 2
ADTV_ROLLING_WINDOW = 50
ATR_WINDOWS = (5, 10, 20)

# 유동성 임계값
KOREAN_LIQUIDITY_THRESHOLD_BASE = 10_000_000
USA_LIQUIDITY_THRESHOLD = 20_000_000

# 볼륨 가중치 프로파일
WEIGHT_PROFILE_UNIFORM = "uniform"
WEIGHT_PROFILE_FRONT_LOADED = "front_loaded"
WEIGHT_PROFILE_BOTTOM_LOADED = "bottom_loaded"
WEIGHT_PROFILE_MIDDLE_LOADED = "middle_loaded"
